### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by unikatdynamik** [unikatdynamik/HISE-COLLAB#3]

**Comment by davidhealey** [comment]
Do you mean changing all the images? If so, it's not really doable.

**Comment by unikatdynamik** [comment]
Yes! My plan was a combobox etc for swapping skins. Or simply changing the images inside the folder. 
But I guess it won't work because those images are embedded right? So the only way is to compile multiple versions?!

**Comment by davidhealey** [comment]
You can make multiple versions of you can duplicate the controls using different images for each set and hide/show one set at a time, but this will make your plugin very bloated.

**Comment by unikatdynamik** [comment]
But I won't need to add additional knobs etc. All skins are looking great with the actual ones. They are pretty neutral but I would add the color picker and vector knobs and elements to change the red highlights and other things.
